server:
  port: 6364

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: uat.kian.digital:9092
          zkNodes: uat.kian.digital:2181
        bindings:
          notificationV4:
            consumer.autoCommitOffset: false
          notification:
            consumer.autoCommitOffset: false
      bindings:
        notificationV4:
          destination: notificationV4
          contentType: application/json
        notification:
          destination: notification
          contentType: application/json
